/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 5030$
 * $Date: 2014-02-10$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		5030
#define SVN_REVSTR	"5030"
#define SVN_REVDATE	"2014-02-10"
#define SVN_REVSTAMP	20140210L
#define SVN_REVMODIFIED	0

#endif /* SVN_REV_H */
